ECOCEANO/Models/Ventas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ECOCEANO.Models
{
    public class Ventas
    {
        internal DateTime fechaRegistro;

        public Ventas()
        {
            //Valores por Default 
            this.estatus = true;
        }
        //Propiedades 
        //Propiedades 
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }


        public int Articulos { get; set; }

        [Display(Name = "MontoTotal")]
        [RegularExpression(@"^\d+(\\\\.\\\\d)?$", ErrorMessage = "0000.0000")]
        [Range(0.1, 200000)]
        public decimal MontoTotal { get; set; }
        public Boolean estatus { get; set; }
        public DateTime fecharegistro { get; set; }

        [Display(Name = "Productos")]
        public int ProductoID { get; set; }
        public Productos Producto { get; set; }



    }
}

ECOCEANO/Controllers/CatalogosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ECOCEANO.Controllers
{
    public class CatalogosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Registro()
        {
            return View();
        }
    }
}

ECOCEANO/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ECOCEANO.Data;
using ECOCEANO.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ECOCEANO.Controllers
{
    public class VentasController : Controller
    {
        private readonly EcoceanoContext con;
        //constructor 
        public VentasController(EcoceanoContext _con)
        {
            con = _con;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var ventaContexto = con.Venta.Include(l => l.Producto);
            return View(await ventaContexto.ToListAsync());
           
        }

        // GET: /<controller>/
        public IActionResult Registro()
        {
            ViewData["ProductoID"] = new SelectList(con.Producto, "ID", "nombre");



            return View();
        }


        //Metodo para registrar
        [HttpPost]
        public async Task<IActionResult> Add([Bind("ID,Articulos,MontoTotal,estatus, ProductoID")] Ventas venta)
        {
            if (ModelState.IsValid)
            {
                venta.fecharegistro = DateTime.Now;
                //Datos de prueba
                venta.estatus = true;
                con.Add(venta);
                //Guardamos cambios 
                await con.SaveChangesAsync();
                //Dirigimos al Index.
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("ErrorProducto", "Los datos no fueron registrados");
                return View("../Ventas", venta);
            }

        }
        /* 
       * INVOCAR LA VISTA DE ELIMINAR
       * */
        public async Task<IActionResult> Borrar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var venta = await con.Venta
                .FirstOrDefaultAsync(m => m.ID == id);
            if (venta == null)
            {
                return NotFound();
            }
            return View(venta);
        }
        /*
         * FUNCION PARA ELIMINAR UN EDITORIAL 
         * 
         */
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EliminarConfirmado(int id)
        {
            //Buscar la editorial a eliminar 
            var venta = await con.Venta.FindAsync(id);
            //Eliminando
            con.Venta.Remove(venta);
            //Guardar cambios en BD 
            await con.SaveChangesAsync();
            //Enviar al Index de editoriales
            return RedirectToAction(nameof(Index));
        }

        /*
         * Invocar la vista Editar
         * localhost:5001/Editoriales/Editar/2
         */
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null) // Si el id es nulo
            {
                return NotFound(); // se envia la pagina indicando que no se encuentra el id
            }
            else
            {
                var venta = await con.Venta
                .FindAsync(id); //se busca en la base de datos la editorial
                if (venta == null)//si no se encuentra
                {
                    return NotFound();
                }
                else // Si se encuentra 
                {
                    return View(venta); //Se envia la editorial a la vista
                }
            }
        }
        /**
         * *Funcion para guardar cambios en la base de datos
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
            Editar(int id, [Bind("ID")] Ventas ventas)
        {
            if (id != ventas.ID)
            {
                return NotFound();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        con.Update(ventas);
                        await con.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        throw;
                    }
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(ventas);
                }
            }
        }
    
    }
}

ECOCEANO/Views/Ventas/Borrar.cshtml
@model Ventas
@{
    ViewData["Title"] = "Borrar";
}
<h3 class=" text-danger">¿Estas seguro de eliminar el registro?</h3>
<div>
    <h3>Ventas</h3>
    <hr />
    <dl class=" row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Articulos)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Articulos)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MontoTotal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MontoTotal)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.estatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.estatus)
        </dd>
    </dl>
    <form asp-action="Eliminar">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Aceptar" class="btn btn-danager" />
        <a asp-action="Index">Regresar a Ventas</a>
    </form>
</div>

ECOCEANO/Views/Ventas/Editar.cshtml
@model Ventas
@{
    ViewData["Title"] = "Editar";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Catalogos" asp-action="Index">Catalogos</a></li>
        <li class="breadcrumb-item"><a asp-controller="Ventas" asp-action="Index">Ventas</a></li>
        <li class="breadcrumb-item active" aria-current="page">Editar</li>
    </ol>
</nav>
<h4>Ventas</h4>
<hr />
<div class=" row">
    <div class=" col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary=" ModelOnly" class=" text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class=" form-group">
                <label asp-for="Articulos" class="control-label"></label>
                <input asp-for="Articulos" class="form-control" />
                <span asp-validation-for="Articulos" class=" text-danger"></span>
            </div>
            <div class=" form-group">
                <label asp-for="MontoTotal" class="control-label"></label>
                <input asp-for="MontoTotal" class="form-control" />
                <span asp-validation-for="MontoTotal" class=" text-danger"></span>
            </div>
            <div class=" form-group">
                <label asp-for="estatus" class="control-label"></label>
                <input asp-for="estatus" class="form-control" />
                <span asp-validation-for="estatus" class=" text-danger"></span>
            </div>
            <div class=" form-group">
                <input type="submit" value="Guardar Cambios" class="btn btn-primary" />
            </div>
        </form>

    </div>

</div>
<div>
    <form asp-action="Editar">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Aceptar" class="btn btn-danager" />
        <a asp-action="Index">Regresar a Ventas</a>
    </form>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ECOCEANO/Views/Ventas/Index.cshtml
@model IEnumerable<Ventas>
@{
    Layout = "_LayoutAdmin";
    ViewData["Title"] = "Ventas";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Catalogos" asp-action="Index">Catalogos</a></li>
        <li class="breadcrumb-item active" aria-current="page">Ventas</li>
    </ol>
</nav>
<section id="nuevaVenta" class="mb-2">
    <a id="btnNuevo" class="btn btn-success" asp-controller="Ventas" asp-action="Registro">
        <i class=" fa fa-file"></i> Nuevo
    </a>
</section>
<!---Listar las editoriales existentes en la BD-->
<section id="ListaProductos">
    <table class="table table-striped table-borderless">
        <thead class=" thead-light">
            <tr>

                <th scope="col">@Html.DisplayNameFor(model => model.Articulos)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.MontoTotal)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.Producto)</th>
               
                <th scope="col">Estatus</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var Ventas in Model)
            {
            <tr>
                <th scope="row">@Html.DisplayFor(model => Ventas.Articulos)</th>
                <td>@Html.DisplayFor(model => Ventas.MontoTotal)</td>

                <td>@Html.DisplayFor(model => Ventas.Producto.nombre)</td>
                <td>@Html.DisplayFor(model => Ventas.estatus)</td>
                <td>
                    <a class="btn btn-primary" asp-action="Editar" asp-route-id="@Ventas.ID">
                        <i class="fas fa-edit"></i>Editar
                    </a>
                    <a class="btn btn-danger" asp-action="Borrar" asp-route-id="@Ventas.ID">
                        <i class="fas fa-trash"></i>Eliminar
                    </a>
                </td>

            </tr>
            }
        </tbody>
    </table>
</section>

ECOCEANO/Views/Ventas/Registro.cshtml
@model Ventas
@{
    Layout = "_LayoutAdmin";
    ViewData["Title"] = "Ventas";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Catalogos" asp-action="Index">Catalogos</a></li>
        <li class="breadcrumb-item"><a asp-controller="Ventas" asp-action="Index">Ventas</a></li>
        <li class="breadcrumb-item active" aria-current="page">Nueva</li>
    </ol>
</nav>

<section id="nuevaVenta">
    <form method="post" asp-controller="Ventas" asp-action="Add">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Articulos" class=" control-label"></label>
            <input asp-for="Articulos" class="form-control" />
            <span asp-validation-for="Articulos" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MontoTotal" class=" control-label"></label>
            <input asp-for="MontoTotal" class="form-control" />
            <span asp-validation-for="MontoTotal" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ProductoID" class=" control-label"></label>
            <select asp-for="ProductoID" asp-items="ViewBag.ProductoID" class=" form-control"></select>
            <span asp-validation-for="ProductoID" class="text-danger"></span>
        </div>

        <div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </form>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}