ECOCEANO/Models/Pedidos.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ECOCEANO.Models
{
    public class Pedidos
    {
        internal DateTime fechaRegistro;
        public Pedidos()
        {
            //Valores por Default 
          
            this.descripcion = "Descripcion";
            this.estatus = true;
        }
        //Propiedades 
        //Propiedades 
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

      

        [Display(Name = "Descripcion")]
        [Required(ErrorMessage = "El campo descripcion es obligatorio")]
        [StringLength(200, ErrorMessage = "Se excedio la longitud maxima permitida.")]
        public String descripcion { get; set; }
        
        public Boolean estatus { get; set; }
        public DateTime fecharegistro { get; set; }

        [Display(Name = "Usuario")]
        public int UsuarioID { get; set; }
        public Usuarios usuario { get; set; }


    }
}

ECOCEANO/Controllers/CatalogosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ECOCEANO.Controllers
{
    public class CatalogosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Registro()
        {
            return View();
        }
    }
}

ECOCEANO/Controllers/PedidosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ECOCEANO.Data;
using ECOCEANO.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ECOCEANO.Controllers
{
    public class PedidosController : Controller
    {
        private readonly EcoceanoContext con;
        //constructor 
        public PedidosController(EcoceanoContext _con)
        {
            con = _con;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var pedidosContexto = con.Pedido.Include(l => l.usuario);
            return View(await pedidosContexto.ToListAsync());

        }

        // GET: /<controller>/
        public IActionResult Registro()
        {
            ViewData["UsuarioID"] = new SelectList(con.Usuario, "ID", "nombre");


            return View();
        }


        //Metodo para registrar
        [HttpPost]
        public async Task<IActionResult> Add([Bind("ID,estatus, descripcion, UsuarioID")] Pedidos pedidos)
        {
            if (ModelState.IsValid)
            {
                pedidos.fecharegistro = DateTime.Now;
                //Datos de prueba
                pedidos.estatus = true;
                con.Add(pedidos);
                //Guardamos cambios 
                await con.SaveChangesAsync();
                //Dirigimos al Index.
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("ErrorProducto", "Los datos no fueron registrados");
                return View("../Pedidos", pedidos);
            }

        }
        /* 
       * INVOCAR LA VISTA DE ELIMINAR
       * */
        public async Task<IActionResult> Borrar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var pedidos = await con.Pedido
                .FirstOrDefaultAsync(m => m.ID == id);
            if (pedidos == null)
            {
                return NotFound();
            }
            return View(pedidos);
        }
        /*
         * FUNCION PARA ELIMINAR UN EDITORIAL 
         * 
         */
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EliminarConfirmado(int id)
        {
            //Buscar la editorial a eliminar 
            var pedidos = await con.Pedido.FindAsync(id);
            //Eliminando
            con.Pedido.Remove(pedidos);
            //Guardar cambios en BD 
            await con.SaveChangesAsync();
            //Enviar al Index de editoriales
            return RedirectToAction(nameof(Index));
        }

        /*
         * Invocar la vista Editar
         * localhost:5001/Editoriales/Editar/2
         */
        public async Task<IActionResult> Editar(int? id)
        {
            if (id == null) // Si el id es nulo
            {
                return NotFound(); // se envia la pagina indicando que no se encuentra el id
            }
            else
            {
                var pedidos = await con.Pedido
                .FindAsync(id); //se busca en la base de datos la editorial
                if (pedidos == null)//si no se encuentra
                {
                    return NotFound();
                }
                else // Si se encuentra 
                {
                    return View(pedidos); //Se envia la editorial a la vista
                }
            }
        }
        /**
         * *Funcion para guardar cambios en la base de datos
         */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>
            Editar(int id, [Bind("ID")] Pedidos pedidos)
        {
            if (id != pedidos.ID)
            {
                return NotFound();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        con.Update(pedidos);
                        await con.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        throw;
                    }
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return View(pedidos);
                }
            }
        }

    }
}

ECOCEANO/Views/Pedidos/Borrar.cshtml
@model Pedidos
@{
    ViewData["Title"] = "Borrar";
}
<h3 class=" text-danger">¿Estas seguro de eliminar el registro?</h3>
<div>
    <h3>Pedidos</h3>
    <hr />
    <dl class=" row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.estatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.estatus)
        </dd>
    </dl>
    <form asp-action="Eliminar">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Aceptar" class="btn btn-danager" />
        <a asp-action="Index">Regresar a Pedidos</a>
    </form>
</div>

ECOCEANO/Views/Pedidos/Editar.cshtml
@model Pedidos
@{
    ViewData["Title"] = "Editar";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Catalogos" asp-action="Index">Catalogos</a></li>
        <li class="breadcrumb-item"><a asp-controller="Pedidos" asp-action="Index">Pedidos</a></li>
        <li class="breadcrumb-item active" aria-current="page">Editar</li>
    </ol>
</nav>
<h4>Pedidos</h4>
<hr />
<div class=" row">
    <div class=" col-md-4">
        <form asp-action="Editar">
            <div asp-validation-summary=" ModelOnly" class=" text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class=" form-group">
                <label asp-for="descripcion" class="control-label"></label>
                <input asp-for="descripcion" class="form-control" />
                <span asp-validation-for="descripcion" class=" text-danger"></span>
            </div>
            <div class=" form-group">
                <label asp-for="estatus" class="control-label"></label>
                <input asp-for="estatus" class="form-control" />
                <span asp-validation-for="estatus" class=" text-danger"></span>
            </div>
            <div class=" form-group">
                <input type="submit" value="Guardar Cambios" class="btn btn-primary" />
            </div>
        </form>

    </div>

</div>
<div>
    <form asp-action="Editar">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Aceptar" class="btn btn-danager" />
        <a asp-action="Index">Regresar a Productos</a>
    </form>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ECOCEANO/Views/Pedidos/Index.cshtml
@model IEnumerable<Pedidos>
@{
    Layout = "_LayoutAdmin";
    ViewData["Title"] = "Pedidos";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Catalogos" asp-action="Index">Catalogos</a></li>
        <li class="breadcrumb-item active" aria-current="page">Pedidos</li>
    </ol>
</nav>
<section id="nuevoPedido" class="mb-2">
    <a id="btnNuevo" class="btn btn-success" asp-controller="Pedidos" asp-action="Registro">
        <i class=" fa fa-file"></i> Nuevo
    </a>
</section>
<!---Listar las editoriales existentes en la BD-->
<section id="ListaProductos">
    <table class="table table-striped table-borderless">
        <thead class=" thead-light">
            <tr>

                <th scope="col">@Html.DisplayNameFor(model => model.descripcion)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.usuario)</th>

                <th scope="col">Estatus</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var pedidos in Model)
            {
            <tr>
                <th scope="row">@Html.DisplayFor(model => pedidos.descripcion)</th>
                <th scope="row">@Html.DisplayFor(model => pedidos.usuario.ID)</th>
                <td>@Html.DisplayFor(model => pedidos.estatus)</td>
                <td>
                    <a class="btn btn-primary" asp-action="Editar" asp-route-id="@pedidos.ID">
                        <i class="fas fa-edit"></i>Editar
                    </a>
                    <a class="btn btn-danger" asp-action="Borrar" asp-route-id="@pedidos.ID">
                        <i class="fas fa-trash"></i>Eliminar
                    </a>
                </td>

            </tr>
            }
        </tbody>
    </table>
</section>

ECOCEANO/Views/Pedidos/Registro.cshtml
@model Pedidos
@{
    Layout = "_LayoutAdmin";
    ViewData["Title"] = "Pedidos";
}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Catalogos" asp-action="Index">Catalogos</a></li>
        <li class="breadcrumb-item"><a asp-controller="Pedidos" asp-action="Index">Pedidos</a></li>
        <li class="breadcrumb-item active" aria-current="page">Nueva</li>
    </ol>
</nav>

<section id="nuevoPedidos">
    <form method="post" asp-controller="Pedidos" asp-action="Add">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="descripcion" class=" control-label"></label>
            <input asp-for="descripcion" class="form-control" />
            <span asp-validation-for="descripcion" class="text-danger"></span>
        </div>
       
            <label asp-for="UsuarioID" class=" control-label"></label>
            <select asp-for="UsuarioID" asp-items="ViewBag.usuarioID" class=" form-control"></select>
            <span asp-validation-for="UsuarioID" class="text-danger"></span>

            <div>
                <div class="form-group">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                </div>
            </div>
    </form>
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}